### ISSUE TITLE
rhd，ho-3d

### ISSUE THREAD

**Issue by wangjiejie2022** [zxz267/SAR#1]
您好！请问有stb和ho-3d的训练代码吗

**Comment by Rhett009** [comment]
bbox_root_freihand_output.json无法下载，有新的链接吗

**Comment by zxz267** [comment]
> bbox_root_freihand_output.json无法下载，有新的链接吗

那个链接不是我维护的，等等看原作者会不会解决这个问题吧。

**Comment by Rhett009** [comment]
> > bbox_root_freihand_output.json无法下载，有新的链接吗
> 
> 那个链接不是我维护的，等等看原作者会不会解决这个问题吧。

请教一下你成功运行了吗
